---
- stat: path=/var/lib/docker
  register: docker_path
- name: make file for dcos block device
  shell: "fallocate -l {{ docker_block_size }}GiB /mnt/docker.disk.image"
  when: not docker_path.stat.exists
- include: roles/common/tasks/mount-device-block.yml
  vars:
    mount_device: /mnt/docker.disk.image
    mount_path:   /var/lib/docker
  when: not docker_path.stat.exists

- name: install docker
  yum:
    name:  https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.03.0.ce-1.el7.centos.x86_64.rpm
- name: set docker permission to user named centos
  user:
    name:   centos
    group:  centos
    groups: docker
    append: yes
- file:
    path:  /etc/docker
    state: directory
- name: docker storage driver is overlay2
  copy:
    content: '{ "storage-driver": "overlay2" }'
    dest: /etc/docker/daemon.json
- name: start docker
  systemd:
    enabled: yes
    name:    docker
    state:   started
