---
- name: create internet gateway
  ec2_vpc_igw:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region:         "{{ region }}"
    #tags:           "{{ igw_tags }}"
    vpc_id:         "{{ vpc_id }}"
  register: igw
- name: save internet gateway ID to aws.ini file
  ini_file:
    dest:    "{{ inifile }}"
    section: network
    option:  igw
    value:   "{{ igw.gateway_id }}"
