---
- name: create subnet
  ec2_vpc_subnet:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    az:             "{{ region + az }}"
    cidr:           "{{ cidr }}"
    region:         "{{ region }}"
    tags:           "{{ subnet_tags }}"
    vpc_id:         "{{ vpc_id }}"
