---
- stat: path=/var/lib/dcos
  register: dcos_path
- name: make file for dcos block device
  shell: "fallocate -l {{ dcos_block_size }}GiB /mnt/dcos.disk.image"
  when: not dcos_path.stat.exists
- include: roles/common/tasks/mount-device-block.yml
  vars:
    mount_device: /mnt/dcos.disk.image
    mount_path:   /var/lib/dcos
  when: not dcos_path.stat.exists

- stat: path=/var/lib/dcos/exhibitor/zookeeper
  register: zk_device
- include: roles/common/tasks/mount-device-block.yml
  vars:
    mount_device: /dev/nvme1n1
    mount_path:   /var/lib/dcos/exhibitor/zookeeper
  when: dcos_mode == 'master' and not zk_device.stat.exists

- name: add groups
  group:
    name:  nogroup
    state: present

- name: install utilities
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - xz
  - unzip
  - curl
  - ipset

- shell: grep "^SELINUX=enforcing" /etc/selinux/config
  ignore_errors: yes
  register: selinux_turnoffed
- name: turn off SELinux
  lineinfile:
    path:   /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    line:   'SELINUX=permissive'
  when: selinux_turnoffed.stdout != ""
  register: turnoff_selinux

- name: reboot
  shell: sleep 2 && /sbin/shutdown -r now "reboot for DC/OS installation preflight"
  async: 1
  poll:  0
  ignore_errors: yes
  when:  turnoff_selinux.changed
- pause: seconds=10
  when:  turnoff_selinux.changed
- wait_for_connection:
    dealy: 5
  when:  turnoff_selinux.changed

- stat: path=/home/centos/dcos_install.sh
  register: dcos_install
- name: download install script
  get_url:
    url: "http://{{ bootstrap }}/dcos_install.sh"
    dest: /home/centos
    group: centos
    owner: centos
    mode:  0400
  when: not dcos_install.stat.exists

- name: install dcos
  shell: "bash dcos_install.sh {{ dcos_mode }}"
  args:
    chdir: /home/centos
  ignore_errors: yes
