---
- name: "tagging to volume - {{ volume }}"
  ec2_tag:
    aws_access_key: "{{ aws.access_key }}"
    aws_secret_key: "{{ aws.secret_key }}"
    region:         "{{ aws.region }}"
    resource:       "{{ target.block_device_mapping[volume].volume_id }}"
    tags:
      Name:           "{{ volume_name }}"
      organization:   "{{ aws.organization }}"
      owner:          "{{ aws.owner }}"
