---
- name: "remove security group - sg-{{ role }}-{{ item.suffix }}"
  ec2_group:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    name:           "{{ role }}-{{ item.suffix }}"
    region:         "{{ region }}"
    state:          absent
    vpc_id:         "{{ vpc }}"
  register: sg

- name: "remove security group from aws.ini file - sg-{{ role }}-{{ item.suffix }}"
  ini_file:
    dest:     "{{ inifile }}"
    section:  security_groups
    option:   "sg-{{ role }}-{{ item.suffix }}"
    state:    absent
  when: sg.changed
