---
- name: Install InfluxDB servers
  hosts: influxdb
  gather_facts: no
  become: yes

  tasks:
  - include: roles/common/tasks/install-docker.yml
    vars:
      docker_block_size: 16

  - include: roles/common/tasks/install-dcos.yml
    vars:
      bootstrap: "{{ groups['dcos-bootstrap'][0] }}"
      dcos_block_size: 4
      dcos_mode: slave

  - include: roles/common/tasks/install-telegraf.yml
  - include: roles/common/tasks/install-dcos-filebeat.yml

  #- name: replace resource rules
  #  copy:
  #    src:  roles/influxdb/files/mesos-resources
  #    dest: /var/lib/dcos/mesos-resources
  #  register: mesos_resource
  #- name: remove DC/OS metadata
  #  file:
  #    path:  /var/lib/mesos/slave/meta/slaves
  #    state: absent
  #  when: mesos_resource.changed
  #- name: start docker
  #  systemd:
  #    enabled: yes
  #    name:    dcos-mesos-slave
  #    state:   started
  #  when: mesos_resource.changed

  - name: create directories
    file:
      path:  "/home/influxdb/{{ item }}"
      state: directory
    with_items:
    - conf
    - log
    - data
    - meta
    - wal

  - name: set config
    copy:
      src:  roles/influxdb/files/influxdb.conf
      dest: /home/influxdb/conf/influxdb.conf
    register: config


  # https://docs.influxdata.com/influxdb/v1.5/query_language/authentication_and_authorization/

  # TODO: docker run --rm -it influxdb:1.5.2 influx -host 10.0.0.4
  #       > CREATE DATABASE telegraf_system_v1
  #       > USE telegraf_system_v1
  #       > CREATE USER <username> WITH PASSWORD '<password>' WITH ALL PRIVILEGES
  # WARNING: change ALL PRIVILEGES to smaller grant

  # TODO: docker run --rm -it influxdb:1.5.2 influx -host 10.0.0.5
  #       > CREATE DATABASE telegraf_system_v1
  #       > USE telegraf_system_v1
  #       > CREATE USER <username> WITH PASSWORD '<password>' WITH ALL PRIVILEGES
  # WARNING: change ALL PRIVILEGES to smaller grant
