---
- name: Install Kafka Brokers
  hosts: "kafka-{{ zone }}"
  gather_facts: no
  roles:
  - kafka
  become: yes

  tasks:
  - include: roles/common/tasks/install-telegraf.yml
    vars:
      telegraf_role: kafka

  - include: roles/common/tasks/install-java8.yml


  - name: create group named kafka
    group:
      name: kafka
  - name: create user named kafka
    user:
      #create_home: no  # ansible 2.5 and later
      createhome: no
      group: kafka
      name:  kafka

  - stat: path="/usr/share/kafka_2.12-1.1.0"
    register: kafka_path
  - name: uncompress kafka
    unarchive:
      src:  roles/kafka/files/kafka_2.12-1.1.0.tgz
      dest: /usr/share
    when: not kafka_path.stat.exists
  - name:
    file:
      src:   /usr/share/kafka_2.12-1.1.0
      dest:  /usr/share/kafka
      state: link

  - stat: path=/var/lib/kafka/data0
    register: kafka_path
  - include: roles/common/tasks/mount-device-block.yml
    vars:
      mount_device: /dev/xvdb
      mount_path:   /var/lib/kafka/data0
    when: not kafka_path.stat.exists
  - file:
      path:  /var/lib/kafka/data0
      state: directory
      group: kafka
      owner: kafka
  - file:
      path:  /var/lib/kafka/data0/lost+found
      state: absent

  - stat: path=/var/log/kafka
    register: kafka_log_path
  - name: make file for log block device
    shell: "fallocate -l 1GiB /mnt/kafka_log.disk.image"
    when: not kafka_log_path.stat.exists
  - include: roles/common/tasks/mount-device-block.yml
    vars:
      mount_device: /mnt/kafka_log.disk.image
      mount_path:   /var/log/kafka
    when: not kafka_log_path.stat.exists
  - file:
      path:  /var/log/kafka
      state: directory
      group: kafka
      owner: kafka


  - file:
      path:  /etc/kafka
      state: directory
  - name: create server.properties
    vars:
      log_segment_bytes: 1073741824
      volumes:
      - /var/lib/kafka/data0
    template:
      src:  roles/kafka/templates/server.properties.j2
      dest: /etc/kafka/server.properties

  - name: create systemd service file
    vars:
      jvm_heap_size: 15
    template:
      src:  roles/kafka/templates/kafka.service.j2
      dest: /usr/lib/systemd/system/kafka.service 

  - name: start kafka
    systemd:
      daemon-reload: yes
      enabled: yes
      name:    kafka
      state:   started
