---
- name: Install Logstash
  hosts: "logstash-{{ zone }}"
  gather_facts: no
  environment:
    JAVA_HOME: /usr/share/java
  become: yes

  tasks:
  - name: install logstash
    yum:
      name: https://artifacts.elastic.co/downloads/logstash/logstash-6.2.4.rpm

  - stat: path=/var/lib/logstash
    register: lib_path
  - name: make file for logstash lib block device
    shell: "fallocate -l 4GiB /mnt/logstash_lib.disk.image"
    when: not lib_path.stat.exists
  - include: roles/common/tasks/mount-device-block.yml
    vars:
      mount_device: /mnt/logstash_lib.disk.image
      mount_path:   /var/lib/logstash
    when: not lib_path.stat.exists

  - stat: path=/var/log/logstash
    register: log_path
  - name: make file for logstash log block device
    shell: "fallocate -l 1GiB /mnt/logstash_log.disk.image"
    when: not log_path.stat.exists
  - include: roles/common/tasks/mount-device-block.yml
    vars:
      mount_device: /mnt/logstash_log.disk.image
      mount_path:   /var/log/logstash
    when: not log_path.stat.exists

  - file:
      path: "/var/{{ item }}/logstash"
      owner: logstash
      group: logstash
    with_items:
    - lib
    - log

  - stat: path=/etc/logstash/logstash.yml.bak
    register: settings_backup
  - copy:
      remote_src: yes
      src:  /etc/logstash/logstash.yml
      dest: /etc/logstash/logstash.yml.bak
    when: not settings_backup.stat.exists
  - name: set config file
    template:
      src:  roles/logstash/templates/logstash.yml.j2
      dest: /etc/logstash/logstash.yml

  - stat: path=/etc/logstash/jvm.options.bak
    register: jvm_backup
  - copy:
      remote_src: yes
      src:  /etc/logstash/jvm.options
      dest: /etc/logstash/jvm.options.bak
    when: not jvm_backup.stat.exists
  - name: set jvm options file
    template:
      src:  roles/logstash/templates/jvm.options.j2
      dest: /etc/logstash/jvm.options

  - name: set config file
    vars:
      kafka_consumer_threads: 1
    template:
      src:  roles/logstash/templates/logstash.conf.j2
      dest: /etc/logstash/conf.d/logstash.conf

  - name: install logstash-input-kafka plugin
    shell: /usr/share/logstash/bin/logstash-plugin install logstash-input-kafka

  - name: install logstash-output-elasticsearch plugin
    shell: /usr/share/logstash/bin/logstash-plugin install logstash-output-elasticsearch

  - name: install x-pack for logstash
    shell: /usr/share/logstash/bin/logstash-plugin install x-pack

  - name: make systemd config
    shell: /usr/share/logstash/bin/system-install /etc/logstash/startup.options systemd

  - name: run on systemd
    systemd:
      daemon-reload: yes
      enabled: yes
      name:    logstash
      state:   started
