---
- name: Install HAProxy
  hosts: haproxy
  gather_facts: no
  roles:
  - dcos
  become: yes

  tasks:
  - name: set config file
    template:
      src:  roles/haproxy/templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: 0744

  - name: copy shell commands
    copy:
      src:  "roles/haproxy/files/docker-{{ item }}.sh"
      dest: "/usr/share/haproxy/docker-{{ item }}.sh"
      mode: 0755
    with_items:
    - run
    - stop
    - check
    - reload

  - name:  check haproxy config validation
    shell: /usr/share/haproxy/docker-check.sh
  - name:  reload haproxy docker
    shell: /usr/share/haproxy/docker-reload.sh
