---
- name: Install Marathon-LB External
  hosts: "dcos-slave-mlb-external-{{ zone }}"
  gather_facts: no
  roles:
  - common
  - haproxy
  #- marathon-lb
  become: yes

  tasks:
  - include: roles/common/tasks/install-docker.yml
    vars:
      docker_block_size: 2

  - include: roles/common/tasks/install-telegraf.yml
    vars:
      telegraf_role: dcos-slave

  - include: roles/dcos/tasks/install-dcos.yml
    vars:
      bootstrap: "{{ groups['dcos-bootstrap-' + zone][0] }}"
      dcos_block_size: 4
      dcos_mode: slave

  - include: roles/dcos/tasks/install-dcos-filebeat.yml
    vars:
      beat_tags:
      - dcos
      - slave
      - mlb-external


  - stat: path=/var/log/haproxy
    register: log_path
  - name: make file for log block device
    shell: "fallocate -l 1GiB /mnt/haproxy_log.disk.image"
    when: not log_path.stat.exists
  - include: roles/common/tasks/mount-device-block.yml
    vars:
      mount_device: /mnt/haproxy_log.disk.image
      mount_path:   /var/log/haproxy
    when: not log_path.stat.exists


  - name: create marathon-lb directory
    file:
      path:  "/usr/share/marathon-lb/{{ item }}"
      state: directory
    with_items:
    - src
    - templates

  - name: copy source file to over-write
    copy:
      src:  roles/marathon-lb/files/src/marathon_lb.py
      dest: /usr/share/marathon-lb/src/marathon_lb.py
      mode: 0755

  - name: copy marathon-lb templates
    copy:
      src:  "roles/marathon-lb/files/templates/{{ item }}"
      dest: "/usr/share/marathon-lb/templates/{{ item }}"
    with_items:
    - HAPROXY_BACKEND_HEAD
    - HAPROXY_BACKEND_HTTP_HEALTHCHECK_OPTIONS
    - HAPROXY_BACKEND_HTTP_OPTIONS
    - HAPROXY_BACKEND_SERVER_OPTIONS
    - HAPROXY_HEAD
    - HAPROXY_HTTP_FRONTEND_HEAD


  - name: compile json for marathon
    vars:
      mlb_group: external
    local_action:
      module: template
      src:  roles/marathon-lb/templates/dcos-marathon-lb.json.j2
      dest: "/tmp/mlb-{{ inventory_hostname }}.json"
    become: no

  - name: start or restart DC/OS service
    uri:
      url:    "http://{{ groups['dcos-master-' + zone][0] }}/marathon/v2/apps/{{ zone }}-mlb-external-{{ inventory_hostname }}"
      method: PUT
      body:   "{{ lookup('file', '/tmp/mlb-' + inventory_hostname + '.json') }}"
      body_format: json
      status_code: 200,201

  - name: remove json for marathon
    local_action:
      module: file
      path:  "/tmp/mlb-{{ inventory_hostname }}.json"
      state: absent
    become: no


  - name: copy rsyslog and logrotate config
    copy:
      src:  "roles/haproxy/files/{{ item }}"
      dest: "/etc/{{ item }}.d/haproxy"
      mode: 0744
    with_items:
    - rsyslog
    - logrotate

  - name: run on systemd
    systemd:
      name:  rsyslog
      state: restarted
