---
- name: Install Jenkins Master
  hosts: "jenkins-master-{{ zone }}"
  gather_facts: no
  roles:
  - dcos
  become: yes

  tasks:
  - include: roles/common/tasks/install-docker.yml
    vars:
      docker_block_size: 64

  - include: roles/common/tasks/install-telegraf.yml
    vars:
      telegraf_role: dcos-slave-jenkins-master

  - include: roles/dcos/tasks/install-dcos.yml
    vars:
      bootstrap: "{{ groups['dcos-bootstrap-' + zone][0] }}"
      dcos_block_size: 4
      dcos_mode: slave


  - include: roles/dcos/tasks/install-dcos-filebeat.yml
    vars:
      beat_tags:
      - dcos
      - slave
      - jenkins
      - jenkins-master


  - stat: path=/var/lib/jenkins
    register: lib_path
  - include: roles/common/tasks/mount-device-block.yml
    vars:
      mount_device: /dev/nvme1n1
      mount_path:   /var/lib/jenkins
    when: not lib_path.stat.exists

  - stat: path=/var/log/jenkins
    register: log_path
  - name: make file for jenkins block device
    shell: "fallocate -l 1GiB /mnt/jenkins_log.disk.image"
    when: not log_path.stat.exists
  - include: roles/common/tasks/mount-device-block.yml
    vars:
      mount_device: /mnt/jenkins_log.disk.image
      mount_path:   /var/log/jenkins
    when: not log_path.stat.exists

  # centos uid is 1000 and jenkins need permission 1000
  - name: change permissions
    file:
      path:  "/var/{{ item }}/jenkins"
      group: centos
      owner: centos
    with_items:
    - lib
    - log


  - name: create deploy json
    local_action:
      module: template
      src:  roles/jenkins/templates/dcos-jenkins.json.j2
      dest: "/tmp/dcos-jenkins.json"
    run_once: yes
    become: no

  - name: start or restart DC/OS service
    uri:
      url:    "http://{{ groups['dcos-master-' + zone][0] }}/marathon/v2/apps/{{ zone }}-jenkins"
      method: PUT
      body:   "{{ lookup('file', '/tmp/dcos-jenkins.json') }}"
      body_format: json
      status_code: 200,201

  - name: remove deploy json
    local_action:
      module: file
      path:  "/tmp/dcos-jenkins.json"
      state: absent
    become: no


  - name: change resource rules
    copy:
      src:  roles/jenkins/files/mesos-resources
      dest: /var/lib/dcos/mesos-resources

  - name: remove mesos metadata
    file:
      path:  /var/lib/mesos/slave/meta/slaves/latest
      state: absent

  - name: restart dcos-mesos-slave
    systemd:
      name:    dcos-mesos-slave
      state:   restarted
