---
- name: Install DC/OS Master Agents
  hosts: "dcos-slave-new-{{ zone }}"
  gather_facts: no
  become: yes

  tasks:
  - include: roles/common/tasks/install-docker.yml
    vars:
      docker_block_size: 64

  - include: roles/common/tasks/install-telegraf.yml
    vars:
      telegraf_role: dcos-slave

  - include: roles/dcos/tasks/install-dcos.yml
    vars:
      bootstrap: "{{ groups['dcos-bootstrap-' + zone][0] }}"
      dcos_block_size: 4
      dcos_mode: slave

  - include: roles/dcos/tasks/install-dcos-filebeat.yml
    vars:
      beat_tags:
      - dcos
      - slave
